import React from 'react';
import { StyledTextSectionHeader } from '../styleguides/StyledTextSectionHeader';
import StyledTextBoxDiv from '../styleguides/StyledTextBoxDiv';
import { StyledText } from '../styleguides/StyledText';

export default function PolandTravel() {
    return (
        <StyledTextBoxDiv>
            <StyledTextSectionHeader>Hello China</StyledTextSectionHeader>
            <StyledText> 
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Vulputate enim nulla aliquet porttitor lacus luctus accumsan. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Natoque penatibus et magnis dis parturient montes. Magnis dis parturient montes nascetur ridiculus mus mauris. Donec ac odio tempor orci dapibus ultrices in iaculis nunc. Enim facilisis gravida neque convallis a cras. Ac odio tempor orci dapibus ultrices in. Dictum at tempor commodo ullamcorper a lacus. Ultricies integer quis auctor elit sed vulputate mi sit amet. Consectetur libero id faucibus nisl tincidunt eget nullam non. Sed blandit libero volutpat sed cras.

Iaculis eu non diam phasellus vestibulum. Lectus sit amet est placerat in egestas erat imperdiet sed. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Tincidunt id aliquet risus feugiat. Turpis egestas integer eget aliquet. Nunc congue nisi vitae suscipit tellus mauris a diam. Blandit aliquam etiam erat velit scelerisque in dictum non. Tincidunt arcu non sodales neque sodales ut etiam sit amet. Tristique senectus et netus et malesuada fames ac. Nisi scelerisque eu ultrices vitae. Sit amet dictum sit amet justo donec. Vel fringilla est ullamcorper eget nulla facilisi. Morbi tincidunt ornare massa eget egestas purus viverra. Mi eget mauris pharetra et ultrices neque ornare aenean euismod. Integer feugiat scelerisque varius morbi enim nunc faucibus. Nisi porta lorem mollis aliquam.

Aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices. Turpis egestas integer eget aliquet nibh praesent tristique magna. Cras fermentum odio eu feugiat pretium nibh ipsum consequat nisl. Pellentesque elit eget gravida cum sociis natoque penatibus et. Risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Donec adipiscing tristique risus nec feugiat in. Eget gravida cum sociis natoque penatibus et magnis. Convallis convallis tellus id interdum. Nam aliquam sem et tortor consequat id porta nibh venenatis. Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. In hendrerit gravida rutrum quisque non tellus orci ac. Lobortis scelerisque fermentum dui faucibus in ornare quam. Dui vivamus arcu felis bibendum ut tristique et. Vulputate eu scelerisque felis imperdiet proin fermentum leo vel orci. Faucibus pulvinar elementum integer enim neque volutpat. Ac odio tempor orci dapibus ultrices in iaculis nunc. Sit amet cursus sit amet dictum sit amet justo donec. Fermentum dui faucibus in ornare quam viverra orci.

Pretium lectus quam id leo in. Et netus et malesuada fames. Facilisi nullam vehicula ipsum a arcu cursus vitae. Molestie at elementum eu facilisis sed odio morbi. Morbi leo urna molestie at elementum eu facilisis. Sed nisi lacus sed viverra tellus in hac habitasse. Scelerisque in dictum non consectetur a. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque sit. Fermentum odio eu feugiat pretium nibh ipsum. Porttitor leo a diam sollicitudin. Semper risus in hendrerit gravida rutrum quisque non. Sed lectus vestibulum mattis ullamcorper velit sed. Elementum tempus egestas sed sed risus pretium quam. Ultricies leo integer malesuada nunc vel. Vulputate sapien nec sagittis aliquam. Iaculis urna id volutpat lacus laoreet non curabitur gravida arcu. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Nunc vel risus commodo viverra maecenas. Volutpat blandit aliquam etiam erat velit. Donec pretium vulputate sapien nec sagittis aliquam malesuada.

In hac habitasse platea dictumst quisque sagittis purus sit. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Amet consectetur adipiscing elit duis tristique sollicitudin nibh. Cursus euismod quis viverra nibh. Dui nunc mattis enim ut tellus elementum sagittis. Maecenas volutpat blandit aliquam etiam erat velit. Libero justo laoreet sit amet cursus sit amet dictum. Lectus arcu bibendum at varius vel pharetra vel. Tristique et egestas quis ipsum suspendisse. In aliquam sem fringilla ut. Fusce id velit ut tortor pretium. Rhoncus urna neque viverra justo nec ultrices dui. Amet massa vitae tortor condimentum lacinia quis vel eros. Morbi non arcu risus quis varius. Integer enim neque volutpat ac tincidunt vitae semper. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Ullamcorper a lacus vestibulum sed arcu non. Est ante in nibh mauris cursus mattis molestie a iaculis. Amet cursus sit amet dictum sit amet justo donec enim.

            </StyledText>
        </StyledTextBoxDiv>
    )
}